package com.mydeseret.mydeseret.model.enums;

public enum ApplicationPermission {
    // --- INVENTORY ---
    CATEGORY_CREATE, CATEGORY_READ, CATEGORY_UPDATE, CATEGORY_DELETE,
    ITEM_CREATE, ITEM_READ, ITEM_UPDATE, ITEM_DELETE,
    INVENTORY_ADJUST, // Manual Restock/Count

    // --- PROCUREMENT (SRM) ---
    SUPPLIER_CREATE, SUPPLIER_READ, SUPPLIER_UPDATE, SUPPLIER_DELETE,
    PURCHASE_ORDER_CREATE, PURCHASE_ORDER_READ, PURCHASE_ORDER_UPDATE, PURCHASE_ORDER_DELETE,
    PURCHASE_ORDER_RECEIVE, // Can mark items as arrived
    PURCHASE_ORDER_PAY,     // Can trigger payment

    // --- FINANCE ---
    EXPENSE_CREATE, EXPENSE_READ, EXPENSE_UPDATE, EXPENSE_DELETE,
    FINANCIAL_REPORT_READ, // View P&L

    // --- MANUFACTURING ---
    BLUEPRINT_CREATE, BLUEPRINT_READ, BLUEPRINT_UPDATE, BLUEPRINT_DELETE,
    MANUFACTURING_BUILD, // Can execute a production run

    // --- SALES (CRM) ---
    CUSTOMER_CREATE, CUSTOMER_READ, CUSTOMER_UPDATE, CUSTOMER_DELETE,
    SALE_CREATE, SALE_READ, SALE_DELETE, SALE_UPDATE,  // Refund/Void
    
    // --- HR & PAYROLL ---
    EMPLOYEE_CREATE, EMPLOYEE_READ, EMPLOYEE_UPDATE, EMPLOYEE_DELETE,
    PAYROLL_GENERATE, PAYROLL_READ, PAYROLL_PROCESS,
    TASK_CREATE, TASK_READ, TASK_UPDATE, TASK_DELETE,

    // --- INTERNAL REQUESTS ---
    REQUISITION_CREATE,   // Ask for stuff
    REQUISITION_APPROVE,  // Say Yes/No (Managers)
    REQUISITION_READ,
    
    // --- SYSTEM ---
    USER_READ, USER_UPDATE,
    ROLE_READ, ROLE_CREATE, ROLE_UPDATE, ROLE_DELETE, // Manage roles

    LOG_READ
}